name: Generate Project Summary

on:
  push:
    branches:
      - main  # replace 'main' with the name of your default branch, if different

jobs:
  generate_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any required dependencies here, for example:
          # pip install some_dependency

      - name: Generate project summary
        run: |
          python utils/project_analyzer.py . > docs/project_summary.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/project_summary.md
          git commit -m "Update project_summary.md" || echo "No changes to commit"
          git push
